version: '3.7'

networks:
  fullstack-net:

services:

  frontend:
    build:
      context: llm-comparison-ui/
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    restart: always
    depends_on: # Start the depends_on first
      - api
    networks:
      - fullstack-net

  api:
    build:
      context: SpringAIDemo/
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    networks:
      - fullstack-net